const enum TErrCodes {
  NO_ACCESS_TOKEN = "NO_ACCESS_TOKEN",
  NO_REFRESH_TOKEN = "NO_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  WRONG_PASSWORD = "WRONG_PASSWORD",
  ACCESS_DENIED = "ACCESS_DENIED",
  OLD_REFRESH_TOKEN_NOT_FOUND = "OLD_REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USERNAME_TAKEN = "USERNAME_TAKEN",
  PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK",
}

export default TErrCodes;
